#!/bin/bash

set -ex

# Install some applications
sudo apt-get update
sudo apt-get install -y git curl
sudo apt-get install -y tmux xclip vim-gtk vim-athena

# Setup for Vim
git clone git://github.com/yoshizo/dotfiles.git ~/dotfiles

[[ -e ~/.vimrc ]] && mv ~/.vimrc ~/.vimrc.bak
[[ -e ~/.tmux.conf ]] && mv ~/.tmux.conf ~/.tmux.conf.bak
[[ -e ~/.gitconfig ]] && mv ~/.gitconfig ~/.gitconfig.bak
[[ -e ~/.bashrc ]] && mv ~/.bashrc ~/.bashrc.bak

ln -s ~/dotfiles/vimrc ~/.vimrc
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/bashrc ~/.bashrc

# Setup directory
mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/colors ~/.vim/backup

# Install pathogen
# Reference: https://github.com/tpope/vim-pathogen
curl -fLSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Install color scheme
curl -fLSso ~/.vim/colors/jellybeans.vim https://raw.githubusercontent.com/nanotech/jellybeans.vim/master/colors/jellybeans.vim 

# Install plugins
cd ~/.vim/bundle
git clone https://github.com/mattn/emmet-vim.git
git clone https://github.com/Shougo/neomru.vim
git clone https://github.com/Shougo/unite.vim.git
git clone https://github.com/Shougo/vimshell.vim.git
git clone https://github.com/tpope/vim-abolish.git
git clone https://github.com/tpope/vim-fugitive
git clone https://github.com/tpope/vim-surround.git
git clone https://github.com/fatih/vim-go.git
