#!/bin/bash

set -ex

# Install some tools
sudo apt-get update
sudo apt-get install -y git curl jq
sudo apt-get install -y tmux xclip vim-gtk vim-athena vim-gnome

# Install Docker
curl -sSL https://get.docker.com/ | sudo sh
sudo gpasswd -a "$(id -n -u)" docker

# Install docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# Setup for Vim
git clone git://github.com/yoshizo/dotfiles.git ~/dotfiles

[[ -e ~/.vimrc ]] && mv ~/.vimrc ~/.vimrc.bak
[[ -e ~/.tmux.conf ]] && mv ~/.tmux.conf ~/.tmux.conf.bak
[[ -e ~/.gitconfig ]] && mv ~/.gitconfig ~/.gitconfig.bak
[[ -e ~/.bashrc ]] && mv ~/.bashrc ~/.bashrc.bak

ln -s ~/dotfiles/vimrc ~/.vimrc
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/bashrc ~/.bashrc

# Setup directory
mkdir -p ~/.vim/autoload ~/.vim/colors ~/.vim/backup

# Install color scheme
curl -fLSso ~/.vim/colors/jellybeans.vim https://raw.githubusercontent.com/nanotech/jellybeans.vim/master/colors/jellybeans.vim 

# Create python default workspace
python3 -m venv ~/default
